### ISSUE TITLE
Open Questions

### ISSUE THREAD

**Issue by flofriday** [remusao/Bison-Flex-CPP-template#4]
Hi, thank you for the template it helped me setup a C++ project, but I have some questions.

## 1) Error handling
The parser and the scanners both increment the `error_` member in the driver, however this value is never returned to the caller of any driver method. So how schould the driver user know if the parsing or scanning succeeded or failed?.

And if `error_` shouldn't be used to tell the caller if parsing succeeded what is it's purpose?

## 2) `error_` initialization.
The drivers `error_` member never gets initialized and has therefore an undefined value. Which raises the question why this template increases a counter when the starting value is random?

## 3) Parse return values
What is the purpose of the integer return values on the driver methods if they always return 0 instead of an error? Why not make them void?

**Comment by remusao** [comment]
Hi @flofriday,

Thanks for reaching out. I'll be honest with you, it's been years I did not touch Bison/Flex and I forgot most of it :D But I will try to recollect the little I can anyway; in case that's still helpful for you (if you figure out some of the answers, we could update this project template or documentation for the next person who might stumble upon the same problems).

## 1) Error handling

You are right that the `error_` member does not seem to be used anywhere. I think the intent of the template was not to be complete in any way but to serve as a starting point. Maybe to close the loop, we could have the `parse()` method return the number of errors instead of `0` at the moment. Something like that?
```patch
diff --git a/src/parse/driver.cc b/src/parse/driver.cc
index 5d1dc46..6c59f97 100644
--- a/src/parse/driver.cc
+++ b/src/parse/driver.cc
@@ -30,7 +30,7 @@ namespace parse
     {
         scanner_->switch_streams(&std::cin, &std::cerr);
         parser_->parse();
-        return 0;
+        return error_;
     }
```

## 2) `error_` initialization

Good catch, that looks like a bug, probably missed because we don't use `error_` anywhere in the template. Would something like that make more sense?
```patch
diff --git a/src/parse/driver.cc b/src/parse/driver.cc
index 5d1dc46..609f9ea 100644
--- a/src/parse/driver.cc
+++ b/src/parse/driver.cc
@@ -7,7 +7,8 @@ namespace parse
     Driver::Driver()
         : scanner_ (new Scanner()),
           parser_ (new Parser(*this)),
-          location_ (new location())
+          location_ (new location()),
+          error_ (0)
     {
     }
 ```

## 3) Parse return values

To be honest I don't remember, I'm not sure the goal was for it to make sense as is since the template was meant to provide the base structure of a project using Bison/Flex and not be usable in its own right (apart from providing a template that compiles). My past self probably did not expect this `parse` method to be used as is. Happy to update it to something more meaningful (returning `error_`?).

In any case, if you have the time and willingness, I'd be happy to review and merge any changes that you would think make sense to improve this template :)

I hope that helps,

**Comment by flofriday** [comment]
Hey, that already helps a lot 😊

I started out with your template for my bachelor thesis and since I hadn't touched C++ in a couple of years I was mostly confused if the template just didn't use `error_` or if there was maybe a brilliant usage of it I just couldn't figure out.

For my project I already have modified the error handling and as I want more verbose errors, but I would love to update the template for future users. 😊

**Comment by remusao** [comment]
Thank you very much for taking the time to open the PR. It's now on the main branch!
